/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Riteen;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dioni Ripoll
 */
public class WinEditCxP extends javax.swing.JDialog {

    /**
     * Creates new form WinEditCxP
     */
    public WinEditCxP() {
        initComponents();
        PanelWinProveedor pwcp = new PanelWinProveedor();
        this.add(pwcp, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cxpEdtText = new javax.swing.JTextField();
        buscarCxPBoton = new javax.swing.JButton();
        verCxPBoton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCuentasPorCobrar = new javax.swing.JTable();
        guardarCxPEdt = new javax.swing.JButton();
        cancelarCxPEdt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Riteen - Cuentas por Pagar");
        setResizable(false);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Cuentas por Pagar");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar Acreedor:");

        cxpEdtText.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        cxpEdtText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxpEdtTextActionPerformed(evt);
            }
        });
        cxpEdtText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cxpEdtTextKeyTyped(evt);
            }
        });

        buscarCxPBoton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarCxPBoton.setText("Buscar");
        buscarCxPBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCxPBotonActionPerformed(evt);
            }
        });

        verCxPBoton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        verCxPBoton.setText("Ver todas las CxP");
        verCxPBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCxPBotonActionPerformed(evt);
            }
        });

        jTableCuentasPorCobrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Acreedor", "Concepto", "Plazo", "Total"
            }
        ));
        jScrollPane3.setViewportView(jTableCuentasPorCobrar);

        guardarCxPEdt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guardarCxPEdt.setText("Guardar");

        cancelarCxPEdt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cancelarCxPEdt.setText("Cancelar");
        cancelarCxPEdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCxPEdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verCxPBoton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(cxpEdtText)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(buscarCxPBoton))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(guardarCxPEdt)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarCxPEdt)))
                .addGap(0, 79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cxpEdtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCxPBoton))
                .addGap(18, 18, 18)
                .addComponent(verCxPBoton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarCxPEdt)
                    .addComponent(cancelarCxPEdt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxpEdtTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxpEdtTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxpEdtTextActionPerformed

    private void cancelarCxPEdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCxPEdtActionPerformed
        int opc = JOptionPane.showConfirmDialog(this, "¿Desea cancelar los cambios realizados?", "Salir", JOptionPane.YES_NO_OPTION);
        
        if(opc == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_cancelarCxPEdtActionPerformed

    private void verCxPBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCxPBotonActionPerformed
        limpiarTabla();
        buscarCuentas();
    }//GEN-LAST:event_verCxPBotonActionPerformed

    private void buscarCxPBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCxPBotonActionPerformed
        verCxPBotonActionPerformed(null);
    }//GEN-LAST:event_buscarCxPBotonActionPerformed

    private void cxpEdtTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxpEdtTextKeyTyped
        int enter = evt.getKeyChar();
        if (enter == KeyEvent.VK_ENTER){
        verCxPBotonActionPerformed(null);
        }
    }//GEN-LAST:event_cxpEdtTextKeyTyped

     private PreparedStatement read;
     private ResultSet rs;
     private DefaultTableModel dtm;
     
     void limpiarTabla(){
    
        while(jTableCuentasPorCobrar.getRowCount()>0){
        ((DefaultTableModel)jTableCuentasPorCobrar.getModel()).removeRow(0);
        
        }
    }
     void buscarCuentas(){
     try {      
           
             
            read = (PreparedStatement) Conexion.getInstancia().getConexion().prepareStatement("SELECT fecha, acreedor, concepto, plazo, total FROM cuentas_por_pagar WHERE acreedor LIKE '%"+ cxpEdtText.getText() +"%'");
           
            rs = (ResultSet) read.executeQuery();
           
            
            dtm = (DefaultTableModel) this.jTableCuentasPorCobrar.getModel();
            
            while (rs.next()) {
            
            Object [] fila = new Object[5]; 
            
           
            for (int i=0;i<fila.length;i++) {
                    fila[i] = rs.getObject(i+1);
                } 

            
            dtm.addRow(fila);
            if(fila.length == 0){
            
             
                JOptionPane.showMessageDialog(null, "no se encontro nada");
            
            }           
}       
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinEditCxP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinEditCxP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinEditCxP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinEditCxP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WinEditCxP().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCxPBoton;
    private javax.swing.JButton cancelarCxPEdt;
    private javax.swing.JTextField cxpEdtText;
    private javax.swing.JButton guardarCxPEdt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCuentasPorCobrar;
    private javax.swing.JButton verCxPBoton;
    // End of variables declaration//GEN-END:variables
}
