/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Riteen;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dioni Ripoll
 */
public class WinEditCxC extends javax.swing.JDialog {

    /**
     * Creates new form WinEditCxC
     */
    public WinEditCxC() {
        initComponents();
        PanelWinCxC pwcc = new PanelWinCxC();
        this.add(pwcc, BorderLayout.CENTER);
        this.setLocationRelativeTo(null);
    }
    private PreparedStatement read;
    private ResultSet rs;
    private DefaultTableModel dtm;
    
    void buscarCuentas(){
    try {      
           
            read = (PreparedStatement) Conexion.getInstancia().getConexion().prepareStatement("SELECT idCuentaXCobrar, fecha, Descripcion, concepto, Cedula, Telefono, Deudor, plazo, total FROM cuentasxcobrar WHERE deudor LIKE '%"+ cxcEdtText.getText() +"%'");
           
            rs = (ResultSet) read.executeQuery();
           
            
            dtm = (DefaultTableModel) this.jTableCXC.getModel();
            
            while (rs.next()) {
            
            Object [] fila = new Object[9];
            
            
            for (int i=0;i<fila.length;i++) {
                    fila[i] = rs.getObject(i+1);
                }

             
            dtm.addRow(fila);
            if(fila.length == 0){
            
             
                JOptionPane.showMessageDialog(null, "no se encontro nada");
            
            }           
}       
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    void limpiarTabla(){
    
        while(jTableCXC.getRowCount()>0){
        ((DefaultTableModel)jTableCXC.getModel()).removeRow(0);
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cxcEdtText = new javax.swing.JTextField();
        buscarCxCBoton = new javax.swing.JButton();
        verCxCBoton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCXC = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        crearCxC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Riteen - Editar Cuentas por Cobrar");
        setModal(true);
        setPreferredSize(new java.awt.Dimension(750, 510));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cuentas por Cobrar");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar Deudor:");

        cxcEdtText.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        cxcEdtText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxcEdtTextActionPerformed(evt);
            }
        });
        cxcEdtText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cxcEdtTextKeyTyped(evt);
            }
        });

        buscarCxCBoton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        buscarCxCBoton.setText("Buscar");
        buscarCxCBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCxCBotonActionPerformed(evt);
            }
        });

        verCxCBoton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        verCxCBoton.setText("Ver todas las CxC");
        verCxCBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCxCBotonActionPerformed(evt);
            }
        });

        jTableCXC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Descripción", "Concepto", "Cédula", "Telefono", "Deudor", "Plazo", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCXC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCXCMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCXC);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money.png"))); // NOI18N

        crearCxC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        crearCxC.setText("Nueva CxC");
        crearCxC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCxCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(verCxCBoton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(crearCxC))
                                    .addComponent(cxcEdtText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarCxCBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cxcEdtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCxCBoton))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verCxCBoton)
                    .addComponent(crearCxC))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxcEdtTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxcEdtTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxcEdtTextActionPerformed

    private void buscarCxCBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCxCBotonActionPerformed
        limpiarTabla();
        buscarCuentas();
    }//GEN-LAST:event_buscarCxCBotonActionPerformed

    private void verCxCBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCxCBotonActionPerformed
       cxcEdtText.setText("");
        buscarCxCBotonActionPerformed(evt);
    }//GEN-LAST:event_verCxCBotonActionPerformed

    private void cxcEdtTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxcEdtTextKeyTyped
       int enter = evt.getKeyChar();
      if (enter == KeyEvent.VK_ENTER) {
          buscarCxCBotonActionPerformed(null);
        }
    }//GEN-LAST:event_cxcEdtTextKeyTyped

    private void crearCxCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCxCActionPerformed
        WinCxC wxc = new WinCxC();
        wxc.casoCxC = 1;
        wxc.setVisible(true);
    }//GEN-LAST:event_crearCxCActionPerformed

    private void jTableCXCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCXCMouseClicked
        if( jTableCXC.getSelectedRows().length > 0 ) { 
          
           WinCxC wcxc = new WinCxC();
           wcxc.casoCxC = 2;    
          
           wcxc.idCxC = (dtm.getValueAt(jTableCXC.getSelectedRow(), 0).toString() );
           wcxc.fechaCxCText.setText(dtm.getValueAt(jTableCXC.getSelectedRow(), 1).toString());
           wcxc.descripcionCxCText.setText(dtm.getValueAt(jTableCXC.getSelectedRow(), 2).toString());
           wcxc.conceptoCxCText.setText(dtm.getValueAt(jTableCXC.getSelectedRow(), 3).toString());
           wcxc.cedulaCxCText.setText(dtm.getValueAt(jTableCXC.getSelectedRow(), 4).toString());
           wcxc.telefonoCxCText.setText(dtm.getValueAt(jTableCXC.getSelectedRow(), 5).toString());
           wcxc.nombreDeudorCxCText1.setText(dtm.getValueAt(jTableCXC.getSelectedRow(), 6).toString());
           wcxc.plazoCxCText.setText(dtm.getValueAt(jTableCXC.getSelectedRow(), 7).toString());                      
           wcxc.totalCxCText.setText(dtm.getValueAt(jTableCXC.getSelectedRow(), 8).toString());
           wcxc.setVisible(true);
         }
    }//GEN-LAST:event_jTableCXCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinEditCxC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinEditCxC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinEditCxC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinEditCxC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               new WinEditCxC().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCxCBoton;
    private javax.swing.JButton crearCxC;
    private javax.swing.JTextField cxcEdtText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCXC;
    private javax.swing.JButton verCxCBoton;
    // End of variables declaration//GEN-END:variables
}
