/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Riteen;

import java.awt.BorderLayout;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dioni Ripoll
 */
public class WinProveedor extends javax.swing.JDialog{

    /**
     * Creates new form WinProveedor2
     */
    public WinProveedor() {
        initComponents();
        PanelWinProveedor pwp = new PanelWinProveedor();
        this.add(pwp, BorderLayout.CENTER);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        proveedorText = new javax.swing.JTextField();
        telefonoProveedorText = new javax.swing.JFormattedTextField();
        emailProveedorText = new javax.swing.JTextField();
        direccionProveedorText = new javax.swing.JTextField();
        guardarProveedor = new javax.swing.JButton();
        cancelarProveedor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Riteen - Registro de Proveedores");
        setModal(true);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proveedores");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("e-Mail:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dirección:");

        try {
            telefonoProveedorText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        guardarProveedor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guardarProveedor.setText("Guardar");
        guardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarProveedorActionPerformed(evt);
            }
        });

        cancelarProveedor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cancelarProveedor.setText("Cancelar");
        cancelarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarProveedorActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedores.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telefonoProveedorText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(emailProveedorText, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(direccionProveedorText)
                            .addComponent(proveedorText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(guardarProveedor)
                        .addGap(29, 29, 29)
                        .addComponent(cancelarProveedor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proveedorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telefonoProveedorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(emailProveedorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(direccionProveedorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarProveedor)
                    .addComponent(cancelarProveedor))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarProveedorActionPerformed
        if(evt.getSource() == cancelarProveedor){
            this.dispose();
        }
    }//GEN-LAST:event_cancelarProveedorActionPerformed
    private PreparedStatement add;
    int casoProveedor = 0;
    String idProveedor;
    
    private void guardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarProveedorActionPerformed
        
        int prueba = 1;
        if(proveedorText.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre del Proveedor");
            proveedorText.requestFocus();
            prueba = 0;
        }
        else if(telefonoProveedorText.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Ingrese el Teléfono");
            telefonoProveedorText.requestFocus();
            prueba = 0;
        }
        else if(emailProveedorText.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Ingrese el e-mail");
            emailProveedorText.requestFocus();
            prueba = 0;
        }
        else if(direccionProveedorText.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Ingrese la dirección");
            direccionProveedorText.requestFocus();
            prueba = 0;
        }        
        
        if(prueba == 1)
        {
        try {
           
            if (casoProveedor == 1){
            add = Conexion.getInstancia().getConexion().prepareStatement("INSERT INTO proveedores (Nombre, Direccion, Telefono, Email) VALUES ( ?, ?, ?, ?)");
            
           
            add.setString(1, proveedorText.getText().toUpperCase());
            add.setString(2, direccionProveedorText.getText().toUpperCase());
            add.setString(3, telefonoProveedorText.getText().toUpperCase());
            add.setString(4, emailProveedorText.getText().toUpperCase());
            }
            if (casoProveedor == 2){
                    add = Conexion.getInstancia().getConexion().prepareStatement("UPDATE proveedores SET Nombre = '"+
                    proveedorText.getText()+"', Direccion = '"+ direccionProveedorText.getText()+"', Telefono = '"+
                    telefonoProveedorText.getText()+"', Email = '"+ emailProveedorText.getText()+"' WHERE idProveedor ="+idProveedor);
            }
            int exitoso = add.executeUpdate();
            
            if (exitoso == 1){
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
            proveedorText.setText("");
            direccionProveedorText.setText("");
            telefonoProveedorText.setText("");
            emailProveedorText.setText("");
            }
            else {
            
            JOptionPane.showMessageDialog(null, "No se puede registrar el Proveedor");
           
            }
        } 
         
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        this.dispose();
        }
    }//GEN-LAST:event_guardarProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinProveedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarProveedor;
    public javax.swing.JTextField direccionProveedorText;
    public javax.swing.JTextField emailProveedorText;
    private javax.swing.JButton guardarProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField proveedorText;
    public javax.swing.JFormattedTextField telefonoProveedorText;
    // End of variables declaration//GEN-END:variables
}
